services:
  nginx:
    image: nginx:alpine
    ports:
      - "${PORT}:80"
    volumes:
      - ./nginx/nginx.conf.template:/etc/nginx/nginx.conf.template
    environment:
      - ACTIVE_POOL=${ACTIVE_POOL}
    command: >
      sh -c "envsubst < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf && nginx -g 'daemon off;'"
    depends_on:
      - app_blue
      - app_green

  app_blue:
    image: ${BLUE_IMAGE}
    ports:
      - "8081:3000"
    environment:
      - APP_POOL=blue
      - RELEASE_ID=${RELEASE_ID_BLUE}
    volumes:
      - ./app:/app
    working_dir: /app
    command: sh -c "npm install && node server.js"

  app_green:
    image: ${GREEN_IMAGE}
    ports:
      - "8082:3000"
    environment:
      - APP_POOL=green
      - RELEASE_ID=${RELEASE_ID_GREEN}
    volumes:
      - ./app:/app
    working_dir: /app
    command: sh -c "npm install && node server.js"